# Generated by Django 5.2.6 on 2025-09-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='Площадь (кв.м)')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('total_floors', models.IntegerField(verbose_name='Всего этажей')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('metro_distance', models.FloatField(verbose_name='Расстояние до метро (км)')),
                ('predicted_price', models.FloatField(verbose_name='Предсказанная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предсказание цены',
                'verbose_name_plural': 'История предсказаний',
            },
        ),
    ]
